### ISSUE TITLE
Optionally determine the secret key from the secret source value

### ISSUE THREAD

**Issue by carolynvs** [getporter/kubernetes-plugins#107]
Currently every secret resolved by the plugin must be stored in its own k8s secret. It would be great to support having multiple resolvable secret values in a single k8s secret.

The k8s plugin should parse the source secret value, and cut it after the first "period". If there is a substring after a period in the source value, then it should be used as the kubernetes secret key. If there isn't a period in the secret name, then the key defaults to "value".

```yaml
# porter credential set
credentials:
  - name: password
    source:
      secret: secretname.secretkey
```

The above credential set would result in Porter calling Resolve, passing in a secret key of "secret", and a secret value of "secretname.secretkey". The plugin should look for a k8s secret named "secretname" and return the value of the key "secretkey" defined on that k8s secret.
